name: thundra-cli-parser

on:
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - run: ./gradlew clean test --rerun-tasks --stacktrace
      
      - run: ls build/test-results
      - run: ls build/test-results/test
      
      - run: npm config set registry ${{ secrets.THUNDRA_REGISTRY }}
      - run: npm config set _auth ${{ secrets.THUNDRA_REGISTRY_AUTH }}
      
      - name: install cli
        run: npm install -g @thundra/artifact-upload
        
      - name: cli upload reports
        env:
          # NODE_TLS_REJECT_UNAUTHORIZED: 0
          THUNDRA_APIKEY: ${{ secrets.THUNDRA_APIKEY }}
          THUNDRA_AGENT_TEST_PROJECT_ID: ${{ secrets.THUNDRA_AGENT_TEST_PROJECT_ID }}
          THUNDRA_UPLOADER_SIGNER_URL: ${{ secrets.THUNDRA_S3_SIGNER_URL }}
        run: thundra upload -ud ./build/test-results/test --type=TEST -f JUNIT
