name: thundra-ci-parser

on:
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - run: ./gradlew clean test --rerun-tasks --stacktrace
      
      - run: ls build/test-results
      - run: ls build/test-results/test
      
      - name: Archive test results
        uses: actions/upload-artifact@v2
        with:
          name: test-result-junit
          path: build/test-results/test
